# Generated by Django 4.2.5 on 2023-09-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('starting_bid', models.IntegerField()),
                ('image', models.ImageField(upload_to='./images')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
