# Generated by Django 4.2.5 on 2023-09-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='./images'),
        ),
    ]
