# Generated by Django 4.2.5 on 2023-09-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_listing_listing_bid_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(related_name='bids', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highest_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highestBid', to='auctions.bid'),
        ),
    ]
