# Generated by Django 4.2.5 on 2023-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_bids_alter_listing_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_count',
            field=models.IntegerField(default=-1),
        ),
    ]
