# Generated by Django 4.2.5 on 2023-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_bids_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_count',
            field=models.IntegerField(default=-1),
        ),
    ]
