# Generated by Django 4.2.5 on 2023-09-25 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 16, 40, 24, 977417), max_length=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
