# Generated by Django 4.2.5 on 2023-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_datetime_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(max_length=20),
        ),
    ]
