# Generated by Django 4.2.5 on 2023-09-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auctions/default_image.png', upload_to='auctions/'),
        ),
    ]
